const WELCOME = "WELCOME"

const MESSAGE = "MESSAGE"
const RECIVED_MESSAGES = "RECIVED_MESSAGES"

const TRIGGERINGREQUEST = "TRIGGERINGREQUEST"





export { WELCOME, MESSAGE, TRIGGERINGREQUEST, RECIVED_MESSAGES }